"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Gavel, LockKeyhole } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { saveRoomSession, type RoomSession } from "@/lib/room-session";
export default function CreatePage() {
  const router = useRouter(); const [minimum, setMinimum] = useState(20); const [timer, setTimer] = useState(10); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const create = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/auction/room", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "create", displayName: name || "Host", minimumSquadSize: minimum, timerSeconds: timer }) }); const json = await response.json() as RoomSession & { error?: string }; if (!response.ok) throw new Error(json.error); saveRoomSession(json); router.push("/lobby"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create room"); } finally { setBusy(false); } };
  return <main className="site-shell"><nav className="topbar"><Link className="brand" href="/"><span className="brand-mark"><Gavel size={17} /></span><span>AUCTION<br /><i>ROOM</i></span></Link><Link href="/" className="nav-link"><ArrowLeft size={14} /> Back home</Link></nav><section className="form-shell"><div className="form-head"><p className="eyebrow"><span /> STEP 01 · ROOM SETUP</p><h1>Create your<br /><em>auction room.</em></h1><p>Set the rules, then choose your franchise in the lobby with your friends. The auction starts when the host says so.</p></div><div className="form-grid"><div className="panel"><h2>Room details</h2><label className="field">Display name<input value={name} onChange={e => setName(e.target.value)} placeholder="Your name" maxLength={40} /></label><div className="room-list"><div>Franchise selection <b>In lobby</b></div><div>Private room <b>Invite only</b></div></div></div><div className="panel"><h2>Auction settings</h2><label className="field">Minimum squad requirement<div className="seg">{[15, 20].map(n => <button type="button" className={minimum === n ? "active" : ""} key={n} onClick={() => setMinimum(n)}>{n} players</button>)}</div></label><label className="field">Auction timer<div className="seg">{[5, 8, 10, 15, 20, 25].map(n => <button type="button" className={timer === n ? "active" : ""} key={n} onClick={() => setTimer(n)}>{n}s</button>)}</div></label><div className="room-list"><div>Starting purse <b>₹120 CR</b></div><div>Maximum squad <b>25 players</b></div><div>Overseas squad limit <b>8 players</b></div><div>Player database <b>620 players</b></div></div></div></div><div className="form-actions"><span className="muted"><LockKeyhole size={14} /> Private room by default</span><button className="lime-button" disabled={busy} onClick={() => void create()}>{busy ? "Creating…" : "Create room"} <ArrowRight size={17} /></button></div>{error && <p className="error-banner">{error}</p>}</section></main>;
}
