"use client";

import Link from "next/link";
import { Gavel, Play, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getRoomSession, type RoomSession } from "@/lib/room-session";

type Snapshot = { teams: Array<{ franchise_code: string; team_ovr: number | null; qualification_status: string; xi_locked: boolean }>; tournament: { status?: string; champion_franchise_id?: string | null } | null; matches: Array<{ stage: string; match_number: number; home_franchise_id: string; away_franchise_id: string; home_score: string | null; away_score: string | null; result_text: string | null; conditions: string | null }>; standings: Array<{ franchise_code: string; played: number; won: number; lost: number; points: number; net_run_rate: number }> };

async function readSnapshot(session: RoomSession) { const r = await fetch("/api/post-auction/tournament", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ roomId: session.roomId, sessionKey: session.sessionKey }) }); const data = await r.json() as { error?: string }; if (!r.ok) throw new Error(data.error ?? "TOURNAMENT_FAILED"); return data as unknown as Snapshot; }
async function action(session: RoomSession, command: string) { const r = await fetch("/api/post-auction/action", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ roomId: session.roomId, sessionKey: session.sessionKey, command }) }); const data = await r.json() as { error?: string }; if (!r.ok) throw new Error(data.error ?? "ACTION_FAILED"); return data; }

export function TournamentDashboard() {
  const [session] = useState<RoomSession | null>(() => getRoomSession()); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!session) return; try { setSnapshot(await readSnapshot(session)); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "TOURNAMENT_FAILED"); } }, [session]);
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const id = window.setInterval(() => void load(), 2500); return () => { window.clearTimeout(initial); window.clearInterval(id); }; }, [load]);
  const run = async (command: string) => { if (!session) return; setBusy(true); try { await action(session, command); await load(); } catch (e) { setError(e instanceof Error ? e.message : "ACTION_FAILED"); } finally { setBusy(false); } };
  if (!session) return <main className="site-shell"><section className="form-shell"><h1>Room session<br /><em>not found.</em></h1><Link href="/join" className="lime-button">Join a room</Link></section></main>;
  if (!snapshot) return <main className="site-shell"><section className="form-shell"><p className="eyebrow"><span /> TOURNAMENT CENTRE</p><h1>Loading the<br /><em>competition.</em></h1><p className="muted">{error || "Checking the room state…"}</p></section></main>;
  const completed = snapshot.matches.filter(m => m.home_score && m.away_score); const playoff = completed.filter(m => m.stage !== "LEAGUE");
  return <main className="site-shell"><nav className="topbar"><Link className="brand" href="/"><span className="brand-mark"><Gavel size={17} /></span><span>AUCTION<br /><i>ROOM</i></span></Link><span className="topbar-status"><span className="live-dot" /> TOURNAMENT CENTRE</span><Link href="/xi" className="nav-link">Team setup</Link></nav><section className="form-shell"><p className="eyebrow"><span /> {snapshot.tournament?.status ?? "READY"}</p><h1>From auction<br /><em>to champion.</em></h1><div className="action-row"><button className="lime-button" disabled={busy} onClick={() => void run("CALCULATE_OVR")}><Sparkles size={15} /> Calculate Team OVR</button><button className="lime-button" disabled={busy} onClick={() => void run("START_TOURNAMENT")}><Play size={15} /> Start Tournament</button><button className="outline-button" disabled={busy} onClick={() => void run("SIMULATE_TOURNAMENT")}><ShieldCheck size={15} /> Reveal Results</button></div>{error && <p className="error-banner">{error}</p>}{snapshot.tournament?.champion_franchise_id && <div className="champion"><Trophy size={30} /><p className="eyebrow">CHAMPION</p><h2>🏆 The season has a winner.</h2><p className="muted">The final result is saved and will remain unchanged after refresh.</p></div>}<div className="tournament-grid"><section className="panel"><div className="builder-heading"><h2>Team strength</h2><span className="muted">Hidden player scores stay private</span></div>{snapshot.teams.map(team => <div className="table-row" key={team.franchise_code}><span>•</span><strong>{team.franchise_code}</strong><span>{team.team_ovr ?? "—"}</span><span>{team.xi_locked ? "LOCK" : "SET"}</span><span>{team.qualification_status}</span><span /></div>)}</section><section className="panel"><div className="builder-heading"><h2>Points table</h2></div>{snapshot.standings.length ? snapshot.standings.map((row, index) => <div className="table-row" key={row.franchise_code}><span>{index + 1}</span><strong>{row.franchise_code}</strong><span>{row.played}</span><span>{row.won}</span><span>{row.points}</span><span>{Number(row.net_run_rate ?? 0).toFixed(2)}</span></div>) : <p className="muted">League results will appear here.</p>}</section></div><section className="panel" style={{ marginTop: 16 }}><div className="builder-heading"><h2>{playoff.length ? "Playoffs & final" : "Match centre"}</h2><span className="muted">{completed.length} completed</span></div><div className="match-list">{completed.map(match => <article className="match-card" key={match.match_number}><header><span>{match.stage} · MATCH {match.match_number}</span><span>{match.conditions ?? "Balanced"}</span></header><p><strong>{match.home_score ?? "—"}</strong> <span className="muted">vs</span> <strong>{match.away_score ?? "—"}</strong></p><span className="muted">{match.result_text ?? "Awaiting result"}</span></article>)}</div></section></section></main>;
}
