import { formatAuctionPrice } from "@/lib/auction-pricing";
import { officialAuctionSets, officialPlayers } from "@/lib/ipl-data";

export default function DataVerificationPage() {
  const indian = officialPlayers.filter((player) => !player.overseas).length;
  const overseas = officialPlayers.filter((player) => player.overseas).length;
  const prices = new Map<number, number>();
  for (const player of officialPlayers) prices.set(player.base_price_lakh, (prices.get(player.base_price_lakh) ?? 0) + 1);
  return <main className="site-shell"><section className="form-shell"><div className="form-head"><p className="eyebrow"><span /> DEVELOPMENT VERIFICATION</p><h1>Official auction<br /><em>data layer.</em></h1><p>Read-only verification surface. No performance ratings or auction-order data are exposed.</p></div><div className="hero-metrics" style={{marginTop:42}}><div><strong>{officialPlayers.length}</strong><span>players</span></div><div><strong>{officialAuctionSets.length}</strong><span>sets</span></div><div><strong>{indian}</strong><span>Indian</span></div><div><strong>{overseas}</strong><span>Overseas</span></div></div><div className="room-card"><div className="panel"><p className="eyebrow">RESERVE-PRICE DISTRIBUTION</p><div className="room-list">{[200,150,125,100,75,50,40,30].map(price=><div key={price}><span>{formatAuctionPrice(price)}</span><b>{prices.get(price) ?? 0} players</b></div>)}</div></div><div className="panel"><p className="eyebrow">SETS</p><div className="room-list">{officialAuctionSets.map(set=><div key={set.official_set_code}><span>{set.official_set_code}</span><b>{set.player_count}</b></div>)}</div></div></div><div className="panel" style={{marginTop:18,overflowX:"auto"}}><p className="eyebrow">PLAYER SAMPLE · OFFICIAL SOURCE FIELDS</p><table style={{width:"100%",marginTop:16,borderCollapse:"collapse",fontSize:12}}><thead><tr style={{color:"#8fa3a9",textAlign:"left"}}><th>Sr.</th><th>Player</th><th>Set</th><th>Country</th><th>Role</th><th>Base</th></tr></thead><tbody>{officialPlayers.slice(0,12).map(player=><tr key={player.official_list_sr_no} style={{borderTop:"1px solid #29424b"}}><td style={{padding:"12px 8px 12px 0"}}>{player.official_list_sr_no}</td><td>{player.full_name}</td><td>{player.official_set_code}</td><td>{player.country}</td><td>{player.specialism}</td><td>{formatAuctionPrice(player.base_price_lakh)}</td></tr>)}</tbody></table></div></section></main>;
}
