-- IPL Mega Auction foundation schema.
-- Critical mutations are intentionally reserved for SECURITY DEFINER RPCs in later phases.
create extension if not exists pgcrypto;

create type room_status as enum ('WAITING','RUNNING','PAUSED','ENDED','QUALIFICATION','XI_SELECTION','TEAM_LOCK','TOURNAMENT_READY','SIMULATING','COMPLETED');
create type member_status as enum ('CONNECTED','DISCONNECTED','LEFT');
create type auction_player_status as enum ('AVAILABLE','CURRENT','SOLD','UNSOLD','COMPLETED');

create table franchises (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, accent_color text not null, created_at timestamptz not null default now());
create table rooms (id uuid primary key default gen_random_uuid(), room_code text unique not null, host_member_id uuid, minimum_squad_size integer not null check (minimum_squad_size in (15,20)), maximum_squad_size integer not null default 25 check (maximum_squad_size=25), starting_purse_lakh integer not null default 12000 check (starting_purse_lakh=12000), auction_timer_seconds integer not null default 10 check (auction_timer_seconds in (8,10,15)), privacy text not null default 'PRIVATE' check (privacy in ('PRIVATE','PUBLIC')), status room_status not null default 'WAITING', created_at timestamptz not null default now());
create table room_members (id uuid primary key default gen_random_uuid(), room_id uuid not null references rooms(id) on delete cascade, display_name text not null, franchise_id uuid references franchises(id), status member_status not null default 'CONNECTED', session_key text not null unique, joined_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), unique(room_id, franchise_id));
alter table rooms add constraint rooms_host_member_fk foreign key (host_member_id) references room_members(id);

create table players (id uuid primary key default gen_random_uuid(), official_list_sr_no integer unique not null, official_set_no integer not null, official_set_code text not null, full_name text not null, country text not null, state_association text, specialism text not null, capped_status text not null, overseas boolean not null default false, batting_style text, bowling_style text, wicketkeeper boolean not null default false, base_price_lakh integer not null check (base_price_lakh > 0), image_url text, auction_status auction_player_status not null default 'AVAILABLE', created_at timestamptz not null default now());
create table auction_sets (set_no integer primary key, set_code text unique not null, set_name text not null, display_order integer unique not null);
create table room_auction_queue (id uuid primary key default gen_random_uuid(), room_id uuid not null references rooms(id) on delete cascade, player_id uuid not null references players(id), set_no integer not null references auction_sets(set_no), random_position_in_set integer not null, overall_queue_position integer not null, status auction_player_status not null default 'AVAILABLE', unique(room_id, player_id), unique(room_id, overall_queue_position));
create table auction_state (room_id uuid primary key references rooms(id) on delete cascade, status room_status not null default 'WAITING', current_set_no integer references auction_sets(set_no), current_set_code text, current_player_id uuid references players(id), current_bid_lakh integer not null default 0, highest_bidder_team_id uuid, timer_ends_at timestamptz, timer_remaining_ms_when_paused bigint, paused_at timestamptz, current_queue_position integer, auction_round text not null default 'MAIN', updated_at timestamptz not null default now());
create table bids (id uuid primary key default gen_random_uuid(), room_id uuid not null references rooms(id) on delete cascade, player_id uuid not null references players(id), member_id uuid not null references room_members(id), franchise_id uuid not null references franchises(id), amount_lakh integer not null check (amount_lakh > 0), created_at timestamptz not null default now());
create table squads (id uuid primary key default gen_random_uuid(), room_id uuid not null references rooms(id) on delete cascade, franchise_id uuid not null references franchises(id), member_id uuid not null references room_members(id), purse_remaining_lakh integer not null default 12000, unique(room_id, franchise_id));
create table squad_players (id uuid primary key default gen_random_uuid(), squad_id uuid not null references squads(id) on delete cascade, player_id uuid not null references players(id), purchase_price_lakh integer not null, acquired_at timestamptz not null default now(), unique(squad_id, player_id));
create table playing_xi (id uuid primary key default gen_random_uuid(), squad_id uuid not null references squads(id) on delete cascade, player_id uuid not null references players(id), batting_position integer not null check (batting_position between 1 and 11), locked boolean not null default false, unique(squad_id, player_id), unique(squad_id, batting_position));
create table player_stats (player_id uuid primary key references players(id) on delete cascade, recent_t20_score numeric, recent_form_score numeric, ipl_score numeric, career_t20_score numeric, batting_score numeric, bowling_score numeric, fielding_score numeric, keeping_score numeric, powerplay_batting numeric, middle_overs_batting numeric, death_batting numeric, powerplay_bowling numeric, middle_overs_bowling numeric, death_bowling numeric, overall_hidden_rating numeric, stats_updated_at timestamptz);
create table team_ratings (squad_id uuid primary key references squads(id) on delete cascade, team_ovr integer, xi_quality numeric, balance_score numeric, depth_score numeric, released_at timestamptz);
create table tournaments (id uuid primary key default gen_random_uuid(), room_id uuid unique not null references rooms(id) on delete cascade, status text not null default 'READY', champion_franchise_id uuid references franchises(id), started_at timestamptz, completed_at timestamptz);
create table matches (id uuid primary key default gen_random_uuid(), tournament_id uuid not null references tournaments(id) on delete cascade, stage text not null, match_number integer not null, home_franchise_id uuid references franchises(id), away_franchise_id uuid references franchises(id), home_score text, away_score text, winner_franchise_id uuid references franchises(id), result_text text, played_at timestamptz);
create table standings (id uuid primary key default gen_random_uuid(), tournament_id uuid not null references tournaments(id) on delete cascade, franchise_id uuid not null references franchises(id), played integer not null default 0, won integer not null default 0, lost integer not null default 0, points integer not null default 0, net_run_rate numeric not null default 0, unique(tournament_id, franchise_id));

create index room_members_room_idx on room_members(room_id); create index queue_room_set_idx on room_auction_queue(room_id,set_no); create index bids_room_player_idx on bids(room_id,player_id,created_at); create index players_set_idx on players(official_set_no,official_set_code);

alter table rooms enable row level security; alter table room_members enable row level security; alter table franchises enable row level security; alter table players enable row level security; alter table auction_sets enable row level security; alter table auction_state enable row level security; alter table squads enable row level security; alter table squad_players enable row level security; alter table playing_xi enable row level security; alter table tournaments enable row level security; alter table matches enable row level security; alter table standings enable row level security;
create policy "public can read franchises" on franchises for select using (true); create policy "public can read players" on players for select using (true); create policy "public can read auction sets" on auction_sets for select using (true); create policy "room members can read room" on rooms for select using (true); create policy "room members can read roster" on room_members for select using (true); create policy "room members can read state" on auction_state for select using (true); create policy "room members can read squads" on squads for select using (true); create policy "room members can read squad players" on squad_players for select using (true); create policy "room members can read xi" on playing_xi for select using (true); create policy "room members can read tournament" on tournaments for select using (true); create policy "room members can read matches" on matches for select using (true); create policy "room members can read standings" on standings for select using (true);
