-- Add server-calculated readiness to the existing team workspace response.
-- Existing post-auction functions remain intact; the public/API surface controls manual flow.
create or replace function public.get_team_workspace(p_room_id uuid,p_session_key text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_member uuid; v_squad squads; v_room jsonb; v_players jsonb; v_xi jsonb; v_qualified jsonb; v_qualified_count integer; v_locked_count integer; v_verified integer;
begin
  v_member:=public.assert_room_session(p_room_id,p_session_key); select * into v_squad from squads where room_id=p_room_id and member_id=v_member; select to_jsonb(r)-'host_member_id' into v_room from rooms r where id=p_room_id;
  select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'full_name',p.full_name,'country',p.country,'specialism',p.specialism,'overseas',p.overseas,'wicketkeeper',p.wicketkeeper,'batting_style',p.batting_style,'bowling_style',p.bowling_style,'purchase_price_lakh',sp.purchase_price_lakh,'batting_position',coalesce(x.batting_position,0),'selected',x.id is not null) order by coalesce(x.batting_position,99),lower(p.full_name)),'[]') into v_players from squad_players sp join players p on p.id=sp.player_id left join playing_xi x on x.squad_id=sp.squad_id and x.player_id=sp.player_id where sp.squad_id=v_squad.id;
  select coalesce(jsonb_agg(jsonb_build_object('player_id',x.player_id,'batting_position',x.batting_position,'locked',x.locked) order by x.batting_position),'[]') into v_xi from playing_xi x where x.squad_id=v_squad.id;
  select count(*) into v_qualified_count from squads where room_id=p_room_id and qualification_status='QUALIFIED'; select count(*) into v_locked_count from squads where room_id=p_room_id and qualification_status='QUALIFIED' and xi_locked;
  select coalesce(jsonb_agg(jsonb_build_object('squad_id',s.id,'franchise_id',s.franchise_id,'franchise_code',(select code from franchises f where f.id=s.franchise_id),'owner_name',(select display_name from room_members m where m.id=s.member_id),'qualification_status',s.qualification_status,'xi_locked',s.xi_locked) order by (case when s.xi_locked then 0 else 1 end),(select code from franchises f where f.id=s.franchise_id)),'[]') into v_qualified from squads s where s.room_id=p_room_id and s.qualification_status='QUALIFIED'; select count(*) into v_verified from player_stats;
  return jsonb_build_object('room',v_room,'squad',jsonb_build_object('id',v_squad.id,'franchise_id',v_squad.franchise_id,'purse_remaining_lakh',v_squad.purse_remaining_lakh,'squad_count',(select count(*) from squad_players where squad_id=v_squad.id),'overseas_count',v_squad.overseas_count,'qualification_status',v_squad.qualification_status,'xi_locked',v_squad.xi_locked,'xi_auto_selected',v_squad.xi_auto_selected),'players',v_players,'xi',v_xi,'qualified_teams',v_qualified,'qualified_count',v_qualified_count,'locked_qualified_count',v_locked_count,'all_ready',v_qualified_count>=2 and v_locked_count=v_qualified_count,'verified_profiles',v_verified,'total_profiles',(select count(*) from players));
end; $$;
